server:
  port: 9091
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authify_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: mirfan916152@gmail.com
    password: gnwb evxu pftk wmeo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"






jwt:
  secret:
    key: YbP1VzUqa7uD6SNXvh7Umm7RIMRqlRSdPGph5YBtzgc=
